### ISSUE TITLE
ImageIO.worker.js 404 (Not Found)

### ISSUE THREAD

**Issue by MaxwellMarcus** [InsightSoftwareConsortium/itk-js#382]
I am building a project using react.js. What I am trying to do is convert DICOM files to vtk imageData using itk.

Here is my code:
```async componentDidMount(){
    var files = []
    for (let i = 0; i < 87; i++){
      let url = `${window.location.href}/../dicoms/${i}.dcm`
      let response = await fetch(url)
      let blob = await response.blob()
      files.push(blob)
    }
    image = await readImageDICOMFileSeries(files)

    const imageData= vtkITKHelper.convertItkToVtkImage(image)

  }
```

I am getting this error:
`GET http://localhost:3000/itk/WebWorkers/ImageIO.worker.js 404 (Not Found)`

**Comment by thewtex** [comment]
> GET http://localhost:3000/itk/WebWorkers/ImageIO.worker.js 404 (Not Found)

You want to configure itk.js to find the worker, either by using the UMD module, configuring Webpack, or using the Unpkg.com CDN in your build.  See the Examples Building section here:

https://insightsoftwareconsortium.github.io/itk-js/examples/umd.html

> files.push(blob)

`readImageDICOMFileSeries` requires [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File)'s instead of `Blob`'s. You need to convert the Blob to a File.

Another reference:

https://www.npmjs.com/package/create-itk-app

**Comment by MaxwellMarcus** [comment]
Thank you for your help!
